### PR TITLE
Ovirt plugin

### PR DESCRIPTION
**Pull request by cmarodrigues**
Hi,

We develop the plugin for backup Ovirt virtual machines for Bareos.

Please, fill free to comment and merge if you want.

Regards,
Carlos Rodrigues

### CODE REVIEW

**Comment by sduehr** [comment]
Hi Carlos,

Thank you very much for your contribution, this is appreciated a lot.  We will review and test as soon as possible.

Regards,

Stephan Dühr

**Comment by cmarodrigues** [comment]
Thank you Stephan.

Also, i would like to inform that we have this plugin in production.

Best regards,
Carlos Rodrigues

On Tue, 2018-10-23 at 01:59 -0700, sduehr wrote:
> Hi Carlos,
> Thank you very much for your contribution, this is appreciated a lot.
> We will review and test as soon as possible.
> Regards,
> Stephan Dühr
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Carlos Rodrigues

Engenheiro de Software Sénior

Eurotux Informática, S.A. | www.eurotux.com
(t) +351 253 680 300 (m) +351 911 926 110

**Comment by sduehr** [comment]
Thanks for the latest additional code for handling snapshot remove.
I've read the code, in
https://github.com/eurotux/bareos-contrib/blob/master/fd-plugins/ovirt-plugin/BareosFdPluginOvirt.py#L1219 
when self.snap_service.remove() fail with something else than error code 400, then
the else: break will fall out of the loop although the snapshot removal failed, and it
would also emit the "Removed the snapshot" jobmessage, which wouldn't be true
in that case.

**Comment by sduehr** [comment]
Hi Carlos,
I've been working on improving the snapshot removal handling, see
https://github.com/eurotux/bareos-contrib/pull/4

Regards,

Stephan

**Pull request merged**
